#!/bin/bash
# Quick deployment script for Railway.app

echo "🚀 IoT Sensor Management - Railway.app Deployment"
echo ""
echo "Prerequisites:"
echo "1. Go to https://railway.app and create account"
echo "2. Create new project and connect GitHub repo (jamelswift/Project004)"
echo "3. Select 'backend' folder"
echo ""
echo "Environment Variables to set in Railway:"
echo "  NODE_ENV=production"
echo "  PORT=5000"
echo "  JWT_SECRET=<your-secure-jwt-secret>"
echo "  AWS_REGION=ap-southeast-1"
echo "  AWS_ACCESS_KEY_ID=<from-your-.env-file>"
echo "  AWS_SECRET_ACCESS_KEY=<from-your-.env-file>"
echo "  DYNAMODB_SENSOR_DATA_TABLE=SensorData"
echo "  DYNAMODB_DEVICE_STATUS_TABLE=DeviceStatus"
echo "  DYNAMODB_NOTIFICATION_LOGS_TABLE=NotificationLogs"
echo "  DYNAMODB_USERS_TABLE=Users"
echo ""
echo "Steps:"
echo "1. Push this code to GitHub"
echo "2. In Railway dashboard, create new project"
echo "3. Connect GitHub and select Project004 repository"
echo "4. Select backend folder for Node.js detection"
echo "5. Add environment variables above"
echo "6. Railway will auto-deploy!"
echo ""
echo "After deployment:"
echo "7. Get the public URL from Railway (e.g., https://iot-api.railway.app)"
echo "8. Update frontend NEXT_PUBLIC_API_URL environment variable"
echo "9. Redeploy frontend to Amplify"
